import assert from 'node:assert/strict';
import { createTvHandler, hashKey } from '../api/tv.js';
import { buildTvPlaylist, safeImage, contactWebsite } from '../src/lib/tvPlaylist.ts';
import { baseSeo } from '../src/lib/publicSeo.js';
const env={SUPABASE_URL:'https://database.test',SUPABASE_SERVICE_ROLE_KEY:'server-key',NODE_ENV:'production'};
const requests=[];
let allowed=true,dbFailure=false;
const fetcher=async(url,options)=>{
 requests.push({url,options});
 if(dbFailure)throw new Error('offline');
 if(url.endsWith('/auth/v1/user'))return Response.json({id:'admin-id'});
 if(url.endsWith('/rpc/gdrb_gallery_is_admin'))return Response.json(allowed);
 if(url.endsWith('/rpc/gdrb_tv_activate'))return Response.json('device-id');
 if(url.includes('gdrb_tv_devices?') && options.method==='POST')return Response.json([{id:'device-id',name:'Clube'}]);
 if(url.includes('session_hash='))return Response.json([{id:'device-id'}]);
 return Response.json([]);
};
const handler=createTvHandler({env,fetcher,makeSecret:()=> 'b'.repeat(64)});
async function call(method,body,headers={}){const result={headers:{}};const res={setHeader:(k,v)=>{result.headers[k]=v;},status:(code)=>{result.status=code;return res;},json:(data)=>{result.body=data;return res;}};await handler({method,body,headers},res);return result;}
assert.equal((await call('GET')).status,200);
assert.equal(requests.length,4,'Trial viewing queries only published content');
assert.ok(requests.every(r=>!r.url.includes('gdrb_tv_devices')));
assert.equal((await call('GET',null,{cookie:'gdrb_tv=expired'})).status,200);
assert.equal((await call('POST',{action:'list'},{'content-type':'application/json'})).status,401);
assert.equal((await call('POST',{action:'activate',key:'a'.repeat(64)},{origin:'https://evil.test','content-type':'application/json'})).status,403);
assert.equal((await call('POST',{action:'activate',key:'short'},{'content-type':'application/json'})).status,400);
assert.equal((await call('POST',{action:'activate'})).status,415);
const activation=await call('POST',{action:'activate',key:'a'.repeat(64)},{origin:'https://gdrboavista.pt','content-type':'application/json'});
assert.equal(activation.status,200);
assert.match(activation.headers['Set-Cookie'],/HttpOnly; Secure; SameSite=Strict; Path=\/api\/tv/);
const rpc=requests.find(r=>r.url.endsWith('gdrb_tv_activate'));
assert.equal(JSON.parse(rpc.options.body).key_hash,hashKey('a'.repeat(64)));
assert.ok(!rpc.options.body.includes('a'.repeat(64)));
const feed=await call('GET',null,{cookie:`gdrb_tv=${'b'.repeat(64)}`});
assert.equal(feed.status,200);assert.equal(feed.headers['Cache-Control'],'private, no-store');
assert.ok(requests.some(r=>r.url.includes('gdrb_news?')&&r.url.includes('is_published=eq.true')&&r.url.includes('status=eq.published')));
assert.ok(requests.some(r=>r.url.includes('gdrb_sponsors?')&&r.url.includes('show_on_tv=eq.true')));
assert.ok(requests.some(r=>r.url.includes('gdrb_matches?')&&r.url.includes('status=in.(agendado,terminado,adiado)')));
allowed=false;
assert.equal((await call('POST',{action:'create',name:'Clube'},{authorization:'Bearer non-admin','content-type':'application/json'})).status,403);
allowed=true;
const created=await call('POST',{action:'create',name:'Clube'},{authorization:'Bearer admin','content-type':'application/json'});
assert.equal(created.status,201);assert.match(created.body.activation_url,/\/tv#ativar=[a-f0-9]{64}$/);
assert.ok(requests.some(r=>r.options.method==='POST'&&r.url.includes('gdrb_tv_devices?')&&!r.options.body.includes('b'.repeat(64))));
dbFailure=true;assert.equal((await call('GET',null,{cookie:`gdrb_tv=${'b'.repeat(64)}`})).status,503);
const row={id:'u12',team_name:'Sub-12',opponent:'Alcobaça',status:'terminado',result_outcome:'loss',home_score:null,away_score:null,is_visible:true,match_date:'2026-10-03',match_time:'09:30',football_type:'Futebol 9'};
const data={updated_at:'2026-10-05T12:00:00Z',sponsors:Array.from({length:13},(_,i)=>({id:String(i),name:`Partner ${i}`})),news:[],matches:[row,{...row,id:'hidden',is_visible:false},{...row,id:'old',match_date:'2026-09-01'},{...row,id:'next',status:'agendado',match_date:'2026-10-10'},{...row,id:'early',status:'agendado',match_date:'2026-10-05',match_time:'09:00'}],tournaments:[]};
const playlist=buildTvPlaylist(data,new Date('2026-10-05T12:00:00Z'));
assert.equal(playlist.filter(s=>s.kind==='sponsor').length,13);
assert.equal(new Set(playlist.filter(s=>s.kind==='sponsor').map(s=>s.id)).size,13,'Each partner appears once per cycle');
let sponsorRun=0;for(const slide of playlist){sponsorRun=slide.kind==='sponsor'?sponsorRun+1:0;assert.ok(sponsorRun<=2,'Never run three partner slides consecutively');}
assert.deepEqual(playlist.filter(s=>s.kind==='results').flatMap(s=>s.matches.map(m=>m.id)),['u12']);
assert.deepEqual(playlist.filter(s=>s.kind==='matches').flatMap(s=>s.matches.map(m=>m.id)),['next']);
assert.ok(buildTvPlaylist({...data,sponsors:[],matches:[]}).length>=2);
assert.equal(safeImage('javascript:alert(1)'),undefined);assert.equal(contactWebsite('javascript:alert(1)'),'');
assert.equal(baseSeo('/tv').noindex,true);assert.equal(baseSeo('/tv').status,200);
console.log('TV: unrestricted trial viewing, admin authorization, private cookie, origin, hashed keys, published feed, offline failures, all partners, youth results, Lisbon schedule and noindex passed.');
