import { useCallback, useEffect, useState } from 'react';
import { Link } from 'react-router-dom';
import { Monitor, Copy, ExternalLink, Plus, ShieldCheck } from 'lucide-react';
import { supabase } from '../../lib/supabase';
type Device={id:string;name:string;activated_at:string|null;revoked_at:string|null;activation_expires_at:string;session_expires_at:string|null};
async function tvAdmin(action:string,extra:Record<string,string>={}) {
 const {data:{session}}=await supabase.auth.getSession();
 const response=await fetch('/api/tv',{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${session?.access_token || ''}`},body:JSON.stringify({action,...extra})});
 const result=await response.json();if(!response.ok)throw new Error(result.error || 'Não foi possível concluir o pedido.');return result;
}
export function AdminTvPage(){
 const [devices,setDevices]=useState<Device[]>([]);const [name,setName]=useState('Televisão do clube');const [activation,setActivation]=useState('');const [error,setError]=useState('');const [busy,setBusy]=useState(false);const [copied,setCopied]=useState(false);
 const load=useCallback(async()=>{try{setDevices(await tvAdmin('list'));}catch(e){setError((e as Error).message);}},[]);
 useEffect(()=>{let active=true;tvAdmin('list').then(rows=>{if(active)setDevices(rows);}).catch(e=>{if(active)setError(e.message);});return()=>{active=false;};},[]);
 const create=async()=>{setBusy(true);setError('');setCopied(false);try{const result=await tvAdmin('create',{name});setActivation(result.activation_url);await load();}catch(e){setError((e as Error).message);}finally{setBusy(false);}};
 const revoke=async(id:string)=>{setBusy(true);setError('');try{await tvAdmin('revoke',{id});setActivation('');await load();}catch(e){setError((e as Error).message);}finally{setBusy(false);}};
 return <div className="space-y-7"><header><p className="text-xs font-bold uppercase tracking-[.25em] text-red-700">Canal do clube</p><h1 className="mt-3 text-3xl font-black">Boavista TV</h1><p className="mt-3 max-w-3xl text-zinc-600">Notícias, próximos jogos, resultados e parceiros em rotação automática, com atualização a cada minuto.</p></header>
 <div className="grid gap-5 lg:grid-cols-2"><section className="rounded-2xl border border-zinc-200 bg-white p-6"><Monitor className="text-red-700"/><h2 className="mt-4 text-xl font-bold">Ligar uma televisão</h2><ol className="mt-4 list-decimal space-y-3 pl-5 text-zinc-600"><li>Gera um link de ativação abaixo.</li><li>Abre esse link no navegador da televisão, uma única vez.</li><li>Seleciona «Ecrã inteiro». Nas próximas vezes, abre <b>gdrboavista.pt/tv</b>.</li></ol><p className="mt-4 text-sm text-zinc-500">A ativação dura 24 horas e só pode ser usada uma vez. O acesso da televisão dura um ano e pode ser revogado aqui. Se apagar os cookies, gere outro link.</p><label className="mt-6 block text-sm font-bold" htmlFor="tv-device-name">Nome da televisão</label><input id="tv-device-name" maxLength={80} value={name} onChange={e=>setName(e.target.value)} className="mt-2 w-full rounded-lg border border-zinc-200 p-3"/><button disabled={busy||!name.trim()} onClick={()=>void create()} className="mt-4 inline-flex items-center gap-2 rounded-lg bg-red-700 px-5 py-3 font-bold text-white disabled:opacity-50"><Plus size={18}/>Gerar link de ativação</button></section>
 <section className="rounded-2xl bg-[#24180f] p-6 text-white"><ShieldCheck className="text-red-400"/><h2 className="mt-4 text-xl font-bold">Preparada para ficar ligada</h2><ul className="mt-4 list-disc space-y-3 pl-5 text-zinc-300"><li>Sem som, publicidade externa ou menus do site.</li><li>Parceiros com logótipo, mensagem curta e contacto.</li><li>Até sub-12, apenas vitória ou derrota.</li><li>Se a ligação falhar, mantém a emissão até 10 minutos e volta a tentar.</li></ul><div className="mt-6 flex flex-wrap gap-3"><a href="/tv?preview=1" target="_blank" rel="noreferrer" className="inline-flex items-center gap-2 rounded-lg bg-white px-4 py-3 font-bold text-zinc-900"><ExternalLink size={18}/>Pré-visualizar canal</a><Link to="/admin/patrocinadores" className="rounded-lg border border-white/30 px-4 py-3 font-bold">Editar parceiros</Link></div><p className="mt-5 text-sm text-zinc-400">No televisor, desative a suspensão automática. Teclas: ←/→ mudar, espaço pausar e F para ecrã inteiro.</p></section></div>
 {error&&<p role="alert" className="rounded-lg bg-red-50 p-4 text-red-800">{error}</p>}
 {activation&&<section className="rounded-2xl border border-red-200 bg-red-50 p-6"><h2 className="font-bold">Link privado de ativação</h2><p className="mt-2 text-sm">Copie para a televisão. Não abra aqui: a primeira abertura associa o acesso a esse navegador.</p><input readOnly aria-label="Link privado de ativação" value={activation} className="mt-4 w-full rounded-lg border border-red-200 bg-white p-3 text-sm" onFocus={e=>e.target.select()}/><button onClick={async()=>{try{await navigator.clipboard.writeText(activation);setCopied(true);}catch{setError('Selecione o link e copie manualmente.');}}} className="mt-3 inline-flex items-center gap-2 font-bold text-red-700"><Copy size={16}/>{copied?'Copiado':'Copiar link'}</button></section>}
 <section className="rounded-2xl border border-zinc-200 bg-white p-6"><h2 className="text-xl font-bold">Televisões</h2><div className="mt-4 divide-y divide-zinc-100">{devices.length===0?<p className="py-4 text-zinc-500">Ainda não existem televisões configuradas.</p>:devices.map(d=><div key={d.id} className="flex flex-wrap items-center justify-between gap-3 py-4"><div><strong>{d.name}</strong><p className="mt-1 text-sm text-zinc-500">{d.revoked_at?'Acesso revogado':d.activated_at?(new Date(d.session_expires_at || 0)<new Date()?'Acesso expirado':'Ativada'):(new Date(d.activation_expires_at)<new Date()?'Link expirado':'A aguardar ativação')}</p></div>{!d.revoked_at&&<button disabled={busy} onClick={()=>void revoke(d.id)} className="rounded-lg border border-red-200 px-4 py-2 text-sm font-bold text-red-700">Revogar acesso</button>}</div>)}</div></section>
 </div>;
}
